/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUserCreateRouteImport } from './routes/_authenticated/user/create'
import { Route as AuthenticatedUserUserIdEditRouteImport } from './routes/_authenticated/user/$userId.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUserCreateRoute = AuthenticatedUserCreateRouteImport.update({
  id: '/user/create',
  path: '/user/create',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUserUserIdEditRoute =
  AuthenticatedUserUserIdEditRouteImport.update({
    id: '/user/$userId/edit',
    path: '/user/$userId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/user/create': typeof AuthenticatedUserCreateRoute
  '/user/$userId/edit': typeof AuthenticatedUserUserIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/user/create': typeof AuthenticatedUserCreateRoute
  '/user/$userId/edit': typeof AuthenticatedUserUserIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/user/create': typeof AuthenticatedUserCreateRoute
  '/_authenticated/user/$userId/edit': typeof AuthenticatedUserUserIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/' | '/user/create' | '/user/$userId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/user/create' | '/user/$userId/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/user/create'
    | '/_authenticated/user/$userId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user/create': {
      id: '/_authenticated/user/create'
      path: '/user/create'
      fullPath: '/user/create'
      preLoaderRoute: typeof AuthenticatedUserCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user/$userId/edit': {
      id: '/_authenticated/user/$userId/edit'
      path: '/user/$userId/edit'
      fullPath: '/user/$userId/edit'
      preLoaderRoute: typeof AuthenticatedUserUserIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedUserCreateRoute: typeof AuthenticatedUserCreateRoute
  AuthenticatedUserUserIdEditRoute: typeof AuthenticatedUserUserIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedUserCreateRoute: AuthenticatedUserCreateRoute,
  AuthenticatedUserUserIdEditRoute: AuthenticatedUserUserIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
